### ISSUE TITLE
Pipe Builder: Newly Inserted Tasks Include UI Info in YAML/JSON

### ISSUE THREAD

**Issue by alwillia** [flexiodata/flexio-web-app#442]
1. Created a new pipe
2. Deleted existing execute task
3. Added a new request task; following task info appeared in YAML:

```
op: sequence
items:
  - op: request
    description: Make an HTTP request; output will be sent to the next step of your pipe.
    bg_color: bg-task-blue
```

4. Issue happens for email task as well, possibly others.
